import { useLanguage } from '../context/LanguageContext';

const POLICY_PARAGRAPHS: Record<'ar' | 'en', string[]> = {
  "ar": [
    "السياسات والشروط القانونية لمنصة ستات بيوت",
    "آخر تحديث: 30 سبتمبر 2026",
    "بيانات الجهة المشغلة",
    "يتم تشغيل منصة ستات بيوت – Setat Byot بواسطة",
    "الاسم القانوني المسجل: مؤسسة ستات بيوت لتصميم المواقع الالكترونية وتحديث البيانات\nالاسم التجاري: ستات بيوت   Setat Byot \nالرقم الضريبي  9595473\nالرقم الوطني للمنشآت  101042113  \nرقم التسجيل لدى وزارة الصناعة والتجارة  588180\nالدولة: المملكة الأردنية الهاشمية\nالموقع الإلكتروني www.setatbyot.com\nالبريد الإلكتروني info@setatbyot.com\nالعنوان:  مجمع السلام ، شارع عارف العنبتاوي، الشميساني، عمّان، الأردن\nالهاتف",
    "96265233400+",
    "+962 7 8823 3400",
    "ويشار إلى الجهة المشغلة في هذه السياسات بـ\"ستات بيوت\" أو \"المنصة\" أو \"نحن\".",
    "الجزء الأول: شروط وأحكام الاستخدام",
    "1. نطاق الخدمة",
    "ستات بيوت منصة إلكترونية وسوق افتراضي يربط العملاء بمجموعة من البائعين ومقدمي الخدمات، بما في ذلك المطابخ المنزلية والإنتاجية، مقدمي خدمات الكيترينج، الحرفيين، أصحاب المشاريع المنزلية، البازارات الافتراضية، ومتاجر ومنتجات أخرى يتم اعتمادها على المنصة.",
    "تشمل خدمات المنصة، بحسب ما هو متاح، عرض المنتجات والخدمات، استقبال وإدارة الطلبات، تسهيل الدفع الإلكتروني، جدولة بعض الطلبات، توفير أو تنسيق خدمات التوصيل، تتبع الطلبات، التقييمات وخدمات الدعم.",
    "ما لم يُذكر خلاف ذلك بوضوح، يكون البائع أو مقدم الخدمة الظاهر اسمه على صفحة المتجر هو المورد المباشر للمنتج أو الخدمة، بينما تعمل ستات بيوت كمنصة إلكترونية تسهّل إتمام المعاملة.",
    "لا يفسر أي بند في هذه السياسات على أنه يعفي ستات بيوت أو البائع من أي التزام أو مسؤولية لا يجوز استبعادها بموجب القانون الأردني.",
    "2. قبول الشروط",
    "باستخدام الموقع أو التطبيق، أو إنشاء حساب، أو تقديم طلب، أو التسجيل كبائع، يقر المستخدم بأنه اطلع على هذه السياسات وفهمها ويوافق على الالتزام بها.",
    "إذا لم يوافق المستخدم على هذه السياسات، فعليه عدم استخدام الخدمات التي تتطلب الموافقة عليها.",
    "3. الأهلية القانونية",
    "يجب أن يكون المستخدم قادرًا قانونًا على إبرام المعاملة ذات الصلة.",
    "ويجب أن يتم استخدام المنصة من قبل القاصرين أو الأشخاص الذين لا يتمتعون بالأهلية القانونية الكاملة تحت إشراف وموافقة ولي أو ممثل قانوني حيثما يتطلب القانون ذلك.",
    "4. حسابات المستخدمين",
    "يلتزم المستخدم بتقديم بيانات صحيحة وحديثة، والحفاظ على سرية بيانات الدخول وعدم إتاحة حسابه للغير بطريقة غير مصرح بها.",
    "يجوز للمنصة اتخاذ إجراءات حماية تشمل التحقق الإضافي أو تعليق الحساب مؤقتًا عند الاشتباه المعقول بوجود احتيال أو استخدام غير مشروع أو اختراق أمني.",
    "على المستخدم إبلاغ ستات بيوت عند الاشتباه باستخدام حسابه دون إذنه.",
    "5. دور ستات بيوت والبائع",
    "تسعى ستات بيوت إلى التعامل مع بائعين ومقدمي خدمات مستوفين لمتطلبات التسجيل المعتمدة لديها.",
    "ويبقى كل بائع مسؤولًا عن المنتجات التي يقوم بإعدادها أو تصنيعها أو عرضها، بما في ذلك صحتها وسلامتها ووصفها وجودتها ومطابقتها للطلب والتزامه بالتراخيص والموافقات التي تتطلبها طبيعة نشاطه.",
    "يجوز لستات بيوت طلب وثائق أو تراخيص من البائع أو إعادة التحقق منها، كما يجوز لها تعليق أو إلغاء اعتماد أي بائع أو منتج عند وجود مؤشرات جدية على مخالفة القانون أو اشتراطات السلامة أو سياسات المنصة.",
    "ولا يشكل اعتماد البائع ضمانًا دائمًا من ستات بيوت بأن البائع سيظل ملتزمًا في جميع الأوقات، ولا يعفي ذلك ستات بيوت من الواجبات الواقعة عليها مباشرةً بموجب القانون.",
    "6. التزامات المطابخ والبائعين الغذائيين",
    "على كل مطبخ أو بائع غذائي الحصول على التراخيص والموافقات السارية المطلوبة من الجهات المختصة لمزاولة نشاطه.",
    "ولا يجوز عرض أو بيع الأغذية عبر المنصة من مطبخ منزلي غير مستوفٍ لمتطلبات الترخيص applicable في المملكة الأردنية الهاشمية.",
    "يلتزم البائع الغذائي بمتطلبات سلامة الغذاء والنظافة والتخزين والتحضير والتعبئة والنقل ودرجات الحرارة المناسبة حسب طبيعة المنتج.",
    "وعليه تقديم وصف صحيح للمنتج ومكوناته الأساسية، والإفصاح بصورة معقولة عن المواد التي قد تسبب الحساسية متى كانت ذات صلة.",
    "7. الحساسية الغذائية",
    "قد تحتوي الأطعمة على مكونات أو آثار لمكونات قد تسبب الحساسية، وقد يتم إعداد أكثر من نوع من الطعام باستخدام مرافق أو معدات مشتركة.",
    "على العميل الذي يعاني من حساسية شديدة أو احتياجات غذائية طبية التأكد من تفاصيل المنتج وإبلاغ البائع أو خدمة العملاء قبل إتمام الطلب عندما يكون ذلك ضروريًا.",
    "لا تعفي هذه المادة أي طرف من المسؤولية القانونية عن تقديم معلومات خاطئة أو مضللة أو عن توفير منتج غير آمن.",
    "8. الحرف اليدوية والمنتجات غير الغذائية",
    "على البائع التأكد من أن السلع والحرف اليدوية المعروضة آمنة وقانونية ومطابقة للوصف والصور والمواصفات المنشورة.",
    "يحظر بيع السلع المقلدة أو المسروقة أو المحظورة قانونًا أو التي تنتهك حقوق الملكية الفكرية أو المنتجات التي يشكل تداولها خطرًا غير معلن على المستهلك.",
    "9. المعلومات والصور",
    "يتحمل البائع مسؤولية دقة المعلومات التي يقدمها عن منتجاته، بما في ذلك الصور والأسعار والأحجام والأوزان والمكونات والمواصفات وأوقات التحضير.",
    "قد تختلف بعض المنتجات المصنوعة يدويًا أو المعدة منزليًا اختلافات بسيطة وغير جوهرية عن الصور بسبب طبيعتها اليدوية، ما لم يكن الاختلاف جوهريًا أو يجعل المنتج غير مطابق لما تم طلبه.",
    "10. الطلبات",
    "قبل تأكيد الطلب، يتم عرض المعلومات المتاحة بشأن المنتجات والسعر ورسوم التوصيل وأي رسوم أخرى مطبقة.",
    "لا يعتبر إرسال الطلب قبولًا نهائيًا له حتى تتم الموافقة عليه وفق آلية المنصة.",
    "يجوز رفض أو إلغاء الطلب في حالات تشمل عدم توفر المنتج، أو عدم قدرة البائع على التنفيذ، أو وجود خطأ واضح في السعر، أو تعذر الدفع، أو تعذر التوصيل، أو وجود اشتباه معقول بالاحتيال أو ظروف خارجة عن السيطرة.",
    "إذا تم تحصيل مبلغ عن طلب أُلغي دون أن يكون الإلغاء ناشئًا عن خطأ العميل، تتم معالجة المبلغ المستحق للاسترداد وفق سياسة الاسترداد.",
    "11. الأسعار",
    "تعرض أسعار المنتجات والخدمات على المنصة قبل تأكيد الطلب.",
    "وقد يتضمن المبلغ النهائي سعر المنتجات، ورسوم التوصيل، وأي ضرائب أو رسوم أو مبالغ أخرى يجب على العميل دفعها، على أن تظهر قبل تأكيد عملية الشراء.",
    "يكون السعر النهائي الظاهر في صفحة تأكيد الطلب هو السعر المعتمد للمعاملة، ما لم يوجد خطأ تقني أو سعري واضح بصورة لا يمكن معها منطقيًا اعتبار السعر صحيحًا.",
    "في حال اكتشاف خطأ واضح قبل تنفيذ الطلب، يتم إبلاغ العميل ومنحه الخيارات المتاحة قانونًا، بما في ذلك إلغاء الطلب واسترداد أي مبلغ تم تحصيله عند الاقتضاء.",
    "12. العروض والقسائم",
    "يجوز لستات بيوت أو البائعين تقديم خصومات أو قسائم أو عروض ترويجية تخضع للشروط المنشورة لكل عرض.",
    "ولا يجوز استبدال القسائم نقدًا ما لم ينص العرض أو القانون على خلاف ذلك.",
    "يجوز إلغاء الاستخدام الاحتيالي أو المتكرر بصورة مخالفة لشروط العرض.",
    "الجزء الثاني: سياسة الدفع الإلكتروني",
    "13. وسائل الدفع",
    "قد تشمل وسائل الدفع المتاحة على المنصة بطاقات Visa وMastercard والدفع النقدي عند الاستلام وأي وسائل إضافية تعتمدها ستات بيوت.",
    "تظهر الوسائل المتاحة فعليًا للعميل عند إتمام الطلب.",
    "14. بوابة الدفع",
    "تتم معالجة مدفوعات البطاقات بواسطة مزود خدمة دفع إلكتروني معتمد، وقد تتم من خلال Middle East Payment Services – MEPS و/أو أي مزود دفع معتمد آخر تتعاقد معه ستات بيوت.",
    "قد يتم نقل العميل إلى صفحة دفع محمية تابعة لمزود الدفع لإدخال بيانات البطاقة والتحقق منها.",
    "15. بيانات البطاقة",
    "عندما تتم عملية الدفع من خلال صفحة الدفع المحمية التابعة لمزود الخدمة، لا تقوم ستات بيوت بتخزين رقم البطاقة الكامل أو رمز CVV/CVC على خوادمها.",
    "إذا اختار العميل ميزة حفظ البطاقة، فقد يستخدم مزود الدفع Token أو مرجع دفع آمن يسمح بعمليات لاحقة دون تخزين رقم البطاقة الكامل لدى ستات بيوت.",
    "لا يتم حفظ رمز CVV/CVC من قبل ستات بيوت لأغراض عمليات الدفع المستقبلية.",
    "16. التحقق الأمني",
    "قد تتطلب عملية الدفع إجراءات تحقق إضافية من البنك المصدر للبطاقة أو شبكة الدفع أو مزود بوابة الدفع.",
    "ويحق لمزود الدفع أو البنك رفض العملية وفق قواعده وأنظمته الأمنية.",
    "17. فشل الدفع",
    "إذا لم يتم اعتماد المعاملة المالية، فقد لا يتم إنشاء أو تأكيد الطلب.",
    "وقد يظهر حجز مؤقت على المبلغ لدى البنك رغم عدم نجاح المعاملة، وفي هذه الحالة تعتمد مدة تحرير المبلغ على البنك أو مزود الدفع.",
    "18. الخصم المكرر",
    "في حال اعتقاد العميل بأنه تم خصم المبلغ أكثر من مرة عن المعاملة ذاتها، عليه التواصل مع ستات بيوت مع تقديم رقم الطلب وأي مرجع للمعاملة.",
    "تقوم ستات بيوت بمراجعة سجلاتها والتنسيق مع مزود الدفع، وعند ثبوت وجود مبلغ مكرر يتم اتخاذ الإجراءات اللازمة لاسترداده.",
    "19. العملة",
    "يتم تحميل العميل بالمبلغ والعملة المبينين على صفحة إتمام الشراء.",
    "عندما يظهر السعر بالدينار الأردني، يتم تنفيذ العملية بالقيمة المعروضة بالدينار الأردني ما لم تظهر معلومات مختلفة بوضوح قبل الدفع.",
    "قد يفرض البنك المصدر للبطاقة رسوم تحويل عملات أو رسومًا مصرفية خاصة به إذا كانت البطاقة أو الحساب بعملة مختلفة، وهذه الرسوم لا تتقاضاها ستات بيوت.",
    "20. الاحتيال",
    "يجوز تعليق أو رفض أو إلغاء معاملة عند وجود مؤشرات أمنية معقولة تدل على استخدام غير مصرح به أو احتيال، على أن يتم ذلك بصورة لا تتعارض مع حقوق المستهلك أو القانون.",
    "الجزء الثالث: سياسة الإلغاء والاسترداد والإرجاع",
    "21. الطلبات الغذائية العادية",
    "يمكن للعميل طلب إلغاء الطلب قبل قبول البائع له أو قبل بدء تحضيره، بحسب حالة الطلب ونظام المنصة.",
    "بعد بدء تحضير الطعام، لا يكون الإلغاء لمجرد تغيير رأي العميل متاحًا بالضرورة، نظرًا لطبيعة الأغذية الطازجة والمعدّة حسب الطلب.",
    "ولا يؤثر ذلك على حق العميل في تقديم شكوى أو طلب تعويض أو استرداد عند وجود عيب أو عدم مطابقة أو مشكلة أخرى يقرها القانون.",
    "22. الطلبات المجدولة والكيترينج",
    "طلبات الكيترينج والمناسبات قد تحتاج إلى حجز وقت مسبق وشراء مواد أو تخصيص عمالة وتحضير خاص.",
    "يجوز تطبيق شروط إلغاء خاصة على هذه الطلبات، على أن تظهر للعميل بوضوح قبل تأكيد الطلب متى كانت هناك رسوم أو مهلة محددة للإلغاء.",
    "إذا لم توجد شروط إلغاء خاصة معروضة عند الحجز، يتم تقييم الإلغاء وفق مرحلة تنفيذ الطلب والتكاليف الفعلية المعقولة وغير القابلة للاسترداد التي ترتبت بصورة مباشرة على الطلب، وذلك في الحدود التي يسمح بها القانون.",
    "ولا يتم خصم مبالغ تقديرية أو جزافية غير معلنة بصورة مسبقة دون أساس معقول.",
    "23. المنتجات المصنوعة حسب الطلب",
    "بالنسبة للحرف أو المنتجات التي يتم تصنيعها أو تخصيصها بناءً على مواصفات العميل، قد لا يكون الإلغاء بسبب تغيير الرأي ممكنًا بعد بدء التصنيع أو التخصيص.",
    "ولا يسري ذلك إذا كان المنتج معيبًا أو غير مطابق للمواصفات المتفق عليها أو مختلفًا بصورة جوهرية عما تم طلبه.",
    "24. الحالات التي تستوجب المراجعة والاسترداد",
    "يمكن للعميل طلب مراجعة الطلب في حال عدم التسليم، أو إلغاء الطلب بعد الدفع، أو تسليم منتج خاطئ، أو وجود نقص جوهري، أو تلف أو عيب، أو وجود منتج غير آمن، أو اختلاف جوهري عن الوصف، أو خصم مبلغ مكرر، أو أي حالة أخرى يمنح فيها القانون حقًا للعميل.",
    "يجوز طلب صور أو بيانات أو معلومات معقولة للتحقق من الحالة، على ألا تستخدم هذه الإجراءات بصورة تعسفية لتعطيل الحقوق القانونية للعميل.",
    "25. طريقة رد الأموال",
    "تتم إعادة المبلغ المستحق عادةً إلى وسيلة الدفع الأصلية متى كان ذلك ممكنًا.",
    "وفي بعض الحالات التي يسمح بها القانون ويوافق عليها العميل، قد يتم تقديم رصيد داخل التطبيق أو وسيلة تعويض بديلة.",
    "لا يتم استبدال رد المبلغ المستحق قانونًا برصيد داخل التطبيق دون موافقة العميل إذا كان له حق قانوني في استرداد المبلغ إلى وسيلة الدفع.",
    "26. مدة الاسترداد",
    "تبدأ ستات بيوت إجراءات رد المبلغ بعد اعتماد الاسترداد دون تأخير غير مبرر.",
    "وقد يحتاج البنك أو مزود الدفع أو شبكة البطاقة بعد ذلك إلى مدة إضافية لإظهار المبلغ في حساب العميل، وهي مدة لا تخضع بالكامل لسيطرة ستات بيوت.",
    "27. المنتجات غير الغذائية",
    "إذا كان المنتج غير الغذائي تالفًا أو معيبًا أو مختلفًا بصورة جوهرية عن وصفه أو تم إرسال منتج آخر بدلًا منه، يتم التعامل معه وفق حقوق المستهلك المقررة قانونًا والسياسة المنشورة.",
    "أما المنتج السليم المطابق للطلب فلا يكون قابلاً للإرجاع لمجرد تغيير الرأي إلا إذا كان البائع أو ستات بيوت قد أعلن عن سياسة إرجاع اختيارية تسمح بذلك أو كان القانون يمنح حقًا بذلك.",
    "الجزء الرابع: سياسة التوصيل",
    "28. عنوان التوصيل",
    "يتحمل العميل مسؤولية إدخال عنوان صحيح ومعلومات اتصال تسمح بإتمام التوصيل.",
    "يجوز استخدام الموقع الجغرافي لتحديد العنوان وحساب المسافة ورسوم التوصيل وتوجيه السائق.",
    "29. أوقات التوصيل",
    "أي وقت تحضير أو توصيل يظهر في المنصة هو تقديري ما لم يتم النص صراحة على كونه موعدًا ملزمًا.",
    "قد تتأثر المدة بحركة المرور أو الطقس أو ضغط الطلبات أو تأخر البائع أو ظروف غير متوقعة.",
    "30. التتبع",
    "قد يتمكن العميل من متابعة حالة الطلب وموقع السائق أثناء تنفيذ عملية التوصيل.",
    "ويتم استخدام موقع السائق لهذا الغرض أثناء الفترة التي يكون فيها السائق Online أو أثناء تنفيذ طلب، وفق إعدادات النظام وسياسة الخصوصية.",
    "31. عدم إمكانية الوصول للعميل",
    "إذا وصل السائق إلى الموقع وتعذر التواصل مع العميل بعد محاولات معقولة، يجوز اتخاذ الإجراء المناسب وفق طبيعة المنتج.",
    "وقد لا يكون من الآمن إعادة توصيل بعض المنتجات الغذائية سريعة التلف بعد مرور فترة طويلة.",
    "ولا يسقط ذلك أي حق للعميل إذا كان فشل التوصيل ناتجًا عن خطأ من البائع أو السائق أو المنصة.",
    "32. الطلب المتضرر أثناء التوصيل",
    "إذا تعرض الطلب لتلف جوهري أثناء التوصيل، على العميل التواصل مع خدمة العملاء في أقرب وقت ممكن، ويتم التحقيق في الحالة واتخاذ الإجراء المناسب، بما في ذلك الاستبدال أو رد المبلغ عندما يكون ذلك مستحقًا",
    "الجزء الخامس: سياسة الخصوصية وحماية البيانات",
    "33. مسؤول البيانات",
    "تُدار منصة ستات بيوت بواسطة مؤسسة ستات بيوت لتصميم المواقع الالكترونية وتحديث البيانات.",
    "وتتم معالجة البيانات الشخصية وفق قانون حماية البيانات الشخصية الأردني والتشريعات والأنظمة والتعليمات السارية ذات العلاقة.",
    "34. البيانات التي قد نجمعها من العملاء",
    "بحسب استخدام الخدمة، قد تشمل البيانات الاسم، رقم الهاتف، البريد الإلكتروني، عنوان التوصيل، الإحداثيات أو الموقع، معلومات الحساب، كلمات المرور بصورتها المحمية، الطلبات السابقة، المنتجات المفضلة، التقييمات، الشكاوى والمراسلات، معلومات الجهاز، سجلات الاستخدام، عنوان IP، بيانات تقنية وأمنية، ومعلومات محدودة عن المعاملات المالية.",
    "35. بيانات البائعين",
    "قد تشمل بيانات البائع اسم الشخص أو المنشأة، الهوية أو وثائق التحقق، معلومات الاتصال، عنوان وموقع النشاط، التراخيص والتصاريح، معلومات المتجر والمنتجات، الصور، بيانات الحساب المالي أو وسائل التسوية، سجل الطلبات والمبيعات والعمولات والمبالغ المسحوبة.",
    "36. بيانات السائقين",
    "قد تشمل بيانات السائق الاسم ومعلومات الاتصال والهوية ورخصة القيادة وبيانات المركبة ووثائقها وموقع السائق أثناء العمل وسجل عمليات التوصيل والأرباح والتقييمات.",
    "37. معلومات الدفع",
    "لا تقوم ستات بيوت، عند استخدام صفحة الدفع المحمية التابعة لمزود الدفع، بتخزين رقم البطاقة الكامل أو CVV/CVC.",
    "قد تستلم المنصة رقم مرجع العملية، حالة الدفع، نوع البطاقة، معلومات بطاقة مقنّعة، أو Token آمن حسب طريقة التكامل مع مزود الدفع.",
    "38. أغراض معالجة البيانات",
    "قد تتم معالجة البيانات من أجل إنشاء وإدارة الحساب، تقديم الخدمة، تنفيذ الطلبات، احتساب التوصيل، معالجة الدفع، ربط العميل بالبائع والسائق، إدارة الطلبات والاستردادات، الدعم الفني وخدمة العملاء، كشف ومنع الاحتيال، حماية المنصة، الالتزام بالقانون، إدارة الحسابات والمستحقات، تحسين الخدمة، وإرسال الاتصالات التسويقية عندما يتوفر الأساس القانوني والموافقات المطلوبة.",
    "39. الموقع الجغرافي",
    "قد يستخدم تطبيق العميل الموقع لعرض البائعين القريبين وتحديد عنوان التوصيل وحساب الرسوم ومتابعة الطلب.",
    "وقد يستخدم تطبيق السائق الموقع، بما في ذلك الموقع في الخلفية أثناء كون السائق Online حيث يكون ذلك ضروريًا، لإظهار الطلبات القريبة وإدارة عمليات التوصيل وتمكين العميل من تتبع طلبه.",
    "يجب ألا يستمر جمع موقع السائق لأغراض التوصيل بعد انتقاله إلى وضع Offline، باستثناء ما يكون ضروريًا قانونًا أو تقنيًا لإتمام عملية بدأت بالفعل.",
    "40. مشاركة البيانات",
    "يجوز مشاركة البيانات الضرورية مع البائع لتنفيذ الطلب، والسائق لإتمام التوصيل، ومزود الدفع لمعالجة المعاملة، ومقدمي الاستضافة والخدمات التقنية والخرائط والرسائل والإشعارات والتحليلات والأمن عند استخدام هذه الخدمات، والمستشارين المهنيين، والجهات الرسمية عندما يفرض أو يسمح القانون بذلك.",
    "يقتصر الإفصاح على البيانات اللازمة للغرض ذي الصلة قدر الإمكان.",
    "لا تبيع ستات بيوت البيانات الشخصية للعملاء إلى المعلنين.",
    "41. بيانات العميل التي يراها البائع أو السائق",
    "يحصل البائع والسائق فقط على المعلومات اللازمة لتنفيذ الطلب بحسب دور كل منهما.",
    "ولا يجوز للبائع أو السائق استخدام بيانات العميل لأغراض شخصية أو تسويقية مستقلة أو الاحتفاظ بها خارج الأنظمة المعتمدة بطريقة غير مشروعة.",
    "42. الموافقة والأساس القانوني",
    "يتم الحصول على الموافقة عندما يتطلب القانون موافقة مسبقة، ويتم الاعتماد على أي أساس آخر يسمح به القانون عند انطباقه.",
    "ويتم تقديم المعلومات المتعلقة بالغرض من جمع البيانات ونطاقها والجهات التي قد تتلقاها بحسب المتطلبات القانونية.",
    "43. حقوق صاحب البيانات",
    "يتمتع صاحب البيانات، وفقًا للقانون والإجراءات المطبقة، بحقوق تشمل معرفة البيانات التي تتم معالجتها، الاطلاع والحصول عليها، تصحيحها وتحديثها، سحب الموافقة عندما تكون المعالجة قائمة عليها، تقييد المعالجة ضمن نطاق معين، طلب المحو أو الإخفاء في الحالات التي يسمح بها القانون، الاعتراض على بعض أنواع المعالجة أو التنميط، نقل نسخة من البيانات حيث ينطبق الحق، ومعرفة الحوادث التي تمس أمن وسلامة بياناته وفقًا للقانون.",
    "يمكن إرسال الطلبات إلى:",
    "info@setatbyot.com",
    "ويجوز طلب معلومات مناسبة للتحقق من هوية مقدم الطلب.",
    "44. التسويق",
    "يجوز إرسال العروض والإشعارات التسويقية عندما يكون ذلك مسموحًا به قانونًا.",
    "يمكن للمستخدم الانسحاب من الاتصالات التسويقية غير الضرورية من خلال الوسيلة المتاحة في التطبيق أو الرسالة.",
    "ولا يؤثر الانسحاب من التسويق على الرسائل الضرورية المتعلقة بالطلبات أو المدفوعات أو الحساب أو الأمان.",
    "45. ملفات تعريف الارتباط والتقنيات المشابهة",
    "قد يستخدم الموقع Cookies أو تقنيات مشابهة لتشغيل الخدمة، تذكر تفضيلات المستخدم، حماية الحساب، قياس الأداء وتحسين تجربة الاستخدام.",
    "وحيث يتطلب القانون موافقة على أنواع معينة من هذه التقنيات، يتم طلب الموافقة المناسبة.",
    "46. مدة الاحتفاظ",
    "لا تحتفظ ستات بيوت بالبيانات إلى أجل غير محدد دون سبب.",
    "يتم الاحتفاظ بالبيانات للمدة اللازمة لتنفيذ الطلبات وإدارة الحسابات وتسوية المدفوعات وحل النزاعات والوفاء بالالتزامات الضريبية والمحاسبية والتنظيمية والأمنية، ثم يتم حذفها أو إخفاء هوية صاحبها عندما لا يعود الاحتفاظ بها ضروريًا، ما لم يوجد التزام قانوني آخر.",
    "47. نقل البيانات خارج الأردن",
    "قد تستضيف بعض الخدمات التقنية أو تعالج البيانات في دول أخرى.",
    "وفي هذه الحالة يتم التعامل مع النقل وفق متطلبات قانون حماية البيانات الشخصية الأردني وأي أنظمة أو تعليمات نافذة بشأن نقل البيانات ومستوى الحماية المطلوب.",
    "48. أمن المعلومات",
    "تستخدم ستات بيوت تدابير فنية وتنظيمية معقولة تتناسب مع طبيعة البيانات والمخاطر المرتبطة بمعالجتها.",
    "لا يمكن ضمان أمن أي نظام إلكتروني بنسبة 100%، إلا أن المنصة تعمل على تقليل مخاطر الوصول أو الاستخدام أو الإفصاح غير المصرح به.",
    "وتتم معالجة أي حادث أمني يتعلق بالبيانات وفق الإجراءات والمتطلبات القانونية المطبقة.",
    "49. الأطفال",
    "المنصة ليست موجهة إلى جمع بيانات الأطفال بصورة مستقلة دون أساس قانوني مناسب.",
    "وعند الحاجة إلى موافقة ولي أو ممثل قانوني لمعالجة بيانات شخص قاصر، يجب الحصول عليها وفق القانون.",
    "50. مراقب حماية البيانات",
    "تلتزم المؤسسة بتعيين واعتماد مراقب لحماية البيانات الشخصية متى انطبقت عليها إحدى الحالات التي يتطلب فيها القانون ذلك.",
    "وعند تعيين مراقب رسمي، يمكن نشر معلومات التواصل الخاصة به أو القناة المخصصة لطلبات حماية البيانات.",
    "الجزء السادس: سياسة وشروط البائعين",
    "51. التسجيل كبائع",
    "يشترط على مقدم الطلب تزويد ستات بيوت بمعلومات صحيحة وكاملة والمستندات المطلوبة للتحقق من هويته ونشاطه.",
    "ولا يعني تقديم الطلب الموافقة التلقائية على فتح متجر.",
    "52. التراخيص",
    "يتحمل البائع مسؤولية استخراج وتجديد جميع الرخص والموافقات المطلوبة لنشاطه.",
    "ويعد استمرار صلاحية هذه المستندات شرطًا لاستمرار عرض المنتجات إذا كانت طبيعة النشاط تتطلبها.",
    "53. المطابخ المنزلية",
    "لا يجوز لبائع الطعام المنزلي استخدام المنصة لبيع منتجات غذائية إذا لم يكن مخولًا قانونًا بممارسة النشاط ولا تتوفر لديه التراخيص والموافقات اللازمة.",
    "يجوز لستات بيوت تعليق المتجر فورًا عند انتهاء الترخيص أو اكتشاف معلومات غير صحيحة أو تلقي إشعار من جهة رسمية أو ظهور خطر جدي على الصحة العامة.",
    "54. التسعير والمخزون",
    "يتحمل البائع مسؤولية تحديث الأسعار والمخزون وأوقات العمل والتحضير بصورة صحيحة.",
    "ولا يجوز رفع السعر بعد قبول طلب العميل إلا بموافقته الصريحة عندما يسمح القانون بذلك.",
    "55. قبول الطلبات",
    "على البائع قبول أو رفض الطلب ضمن وقت معقول والعمل على تحضير الطلب المقبول وفق التفاصيل المتفق عليها.",
    "تكرار قبول الطلبات ثم إلغائها دون سبب مشروع قد يؤدي إلى اتخاذ إجراءات على الحساب.",
    "56. العمولة والمبالغ المستحقة",
    "تحدد عمولة ستات بيوت وأي رسوم مرتبطة بالخدمة وفق اتفاقية البائع أو المعلومات الظاهرة في لوحة تحكم البائع.",
    "ويجب على البائع مراجعة تفاصيل العمولة والمستحقات والتسويات قبل استخدام الخدمة التجارية.",
    "لا تعد هذه السياسة بحد ذاتها بديلًا عن أي اتفاق تجاري منفصل يحدد النسب ومواعيد التحويل والتسوية.",
    "57. الضرائب",
    "يتحمل كل طرف الالتزامات الضريبية الواقعة عليه قانونًا.",
    "ويلتزم البائع بتوفير المعلومات أو الفواتير أو الوثائق التي يتطلبها القانون بحسب طبيعة نشاطه.",
    "58. الإلغاءات والاستردادات الناتجة عن خطأ البائع",
    "إذا تم رد مبلغ للعميل بسبب منتج ناقص أو خاطئ أو معيب أو غير آمن أو بسبب عدم تنفيذ البائع للطلب، يجوز تحميل المبلغ أو الجزء المتعلق بالخطأ على حساب البائع وفق اتفاقية البائع والقانون وبعد التحقق المعقول من الحالة.",
    "59. الشكاوى والتحقيق",
    "يلتزم البائع بالتعاون مع التحقيقات المتعلقة بشكاوى العملاء وتقديم المعلومات اللازمة خلال مدة معقولة.",
    "يجوز لستات بيوت إعادة المبلغ للعميل أو اتخاذ إجراء مؤقت عند وجود خطر صحي أو احتيالي أو عندما تكون الوقائع واضحة، مع مراعاة حقوق الأطراف.",
    "60. محتوى البائع",
    "يمنح البائع ستات بيوت ترخيصًا غير حصري لاستخدام الصور والأسماء والشعارات والأوصاف التي يقدمها بالقدر اللازم لعرض متجره ومنتجاته والترويج لها وتشغيل خدمات المنصة.",
    "ويؤكد البائع أنه يمتلك الحق في استخدام المحتوى الذي يرفعه.",
    "61. الممارسات المحظورة",
    "يحظر على البائع تقديم معلومات مضللة، أو التلاعب بالتقييمات، أو بيع منتجات مخالفة للقانون، أو استخدام معلومات العملاء خارج نطاق تنفيذ الطلب، أو محاولة الاحتيال على نظام الدفع أو العمولات، أو نشر محتوى ينتهك حقوق الغير.",
    "62. تعليق المتجر",
    "يجوز تعليق أو تقييد أو إغلاق المتجر في حالات المخالفة الجوهرية، أو المخاطر الصحية، أو الاحتيال، أو انتهاء التراخيص المطلوبة، أو تكرار الشكاوى المثبتة، أو مخالفة القانون أو شروط المنصة.",
    "حيثما تسمح طبيعة المخالفة بذلك، يمكن إبلاغ البائع بسبب الإجراء ومنحه فرصة لتقديم توضيح أو تصحيح المخالفة.",
    "الجزء السابع: التقييمات والمحتوى",
    "63. تقييمات العملاء",
    "يجوز للعميل تقييم تجربته بعد إتمام الطلب.",
    "يجب أن يكون التقييم قائمًا على تجربة حقيقية وألا يتضمن تهديدًا أو إساءة أو تمييزًا أو تشهيرًا غير مشروع أو معلومات شخصية للآخرين أو محتوى مخالفًا للقانون.",
    "يجوز إزالة المحتوى المخالف دون إزالة الانتقاد المشروع لمجرد أنه سلبي.",
    "الجزء الثامن: المسؤولية",
    "64. مسؤولية البائع",
    "يتحمل البائع المسؤولية عن سلامة وجودة ومطابقة المنتجات التي يصنعها أو يعدها أو يبيعها، وعن صحة بياناتها والتزام نشاطه بالمتطلبات القانونية ذات الصلة.",
    "65. مسؤولية ستات بيوت",
    "تلتزم ستات بيوت بمسؤولياتها كجهة مشغلة للمنصة فيما يتعلق بالخدمات التي تقدمها مباشرة، بما في ذلك ما يفرضه القانون بشأن المعلومات والخصوصية ومعالجة الشكاوى والمدفوعات والخدمات التقنية.",
    "لا تتحمل ستات بيوت مسؤولية خسارة نتجت حصريًا عن معلومات غير صحيحة قدمها المستخدم أو فعل خارج بصورة معقولة عن سيطرة المنصة.",
    "ولا يجوز تفسير أي إخلاء مسؤولية على أنه يستبعد مسؤولية لا يسمح القانون باستبعادها.",
    "66. الظروف الخارجة عن السيطرة",
    "قد تتأثر الخدمات بظروف خارجة بصورة معقولة عن السيطرة، مثل الأحوال الجوية الشديدة، إغلاق الطرق، الكوارث، انقطاع الاتصالات أو أنظمة الدفع، القرارات الرسمية، أو أحداث القوة القاهرة.",
    "تعمل ستات بيوت على تقليل أثر هذه الظروف ومعالجة الطلبات المتأثرة بصورة معقولة.",
    "الجزء التاسع: الملكية الفكرية",
    "67. حقوق ستات بيوت",
    "تعود الحقوق في اسم Setat Byot وتصاميم المنصة والبرمجيات والمحتوى الذي تملكه المؤسسة إلى أصحابها القانونيين.",
    "ولا يجوز نسخ أو استغلال المنصة تجاريًا دون موافقة أو حق قانوني.",
    "68. حقوق البائعين",
    "تبقى حقوق البائع في صوره وعلاماته ومحتواه المملوك له قائمة، مع الترخيص المحدود الممنوح للمنصة لأغراض تشغيل وعرض وتسويق متجره.",
    "الجزء العاشر: إيقاف الحساب وإنهاؤه",
    "69. إنهاء المستخدم لحسابه",
    "يمكن للمستخدم طلب إغلاق حسابه، مع مراعاة الاحتفاظ بالبيانات التي يجب الاحتفاظ بها قانونًا أو اللازمة لتسوية معاملات أو نزاعات قائمة.",
    "70. تعليق الحساب",
    "يجوز تعليق الحساب عند وجود مخالفة جدية أو مخاطر أمنية أو احتيالية، ويجب أن يكون الإجراء متناسبًا مع طبيعة المخالفة قدر الإمكان.",
    "الجزء الحادي عشر: الشكاوى وتسوية النزاعات",
    "71. تقديم الشكاوى",
    "يُنصح العميل أو البائع بالتواصل مع ستات بيوت أولًا بشأن أي شكوى متعلقة بطلب أو دفع أو استرداد أو حساب.",
    "البريد الإلكتروني: info@setatbyot.com\nالهاتف: +962 7 8823 3400",
    "تعمل ستات بيوت على مراجعة الشكوى والمعلومات المتاحة ومحاولة الوصول إلى حل مناسب.",
    "ولا تمنع هذه الإجراءات أي شخص من ممارسة حقه في تقديم شكوى إلى الجهات الحكومية أو التنظيمية المختصة أو اللجوء إلى القضاء.",
    "72. القانون الواجب التطبيق",
    "تخضع هذه السياسات لقوانين المملكة الأردنية الهاشمية.",
    "وتختص الجهات والمحاكم الأردنية ذات الاختصاص بأي نزاع وفق قواعد الاختصاص المعمول بها، مع الحفاظ على حقوق المستهلك وصاحب البيانات وأي حقوق إلزامية أخرى يقررها القانون.",
    "الجزء الثاني عشر: تعديل السياسات",
    "73. التحديثات",
    "يجوز تحديث هذه السياسات عند تغير الخدمة أو المتطلبات القانونية أو التشغيلية.",
    "يتم نشر النسخة المحدثة مع تاريخ آخر تحديث.",
    "وعندما يتطلب تعديل جوهري الحصول على موافقة جديدة أو إشعار خاص بموجب القانون، تتخذ ستات بيوت الإجراءات اللازمة لذلك.",
    "الجزء الثالث عشر: اللغة",
    "74. العربية والإنجليزية",
    "تتوفر هذه السياسات بالعربية والإنجليزية ويقصد بالنسختين التعبير عن الشروط ذاتها.",
    "وعند وجود اختلاف غير مقصود في المعنى أو التفسير، تكون النسخة العربية المرجع لأغراض التعامل داخل المملكة الأردنية الهاشمية إلى الحد الذي يسمح به القانون.",
    "التواصل معنا",
    "مؤسسة ستات بيوت لتصميم المواقع الالكترونية وتحديث البيانات\nSetat Byot",
    "الرقم الضريبي: 9595473\nالرقم الوطني للمنشآت: 101042113\nرقم تسجيل وزارة الصناعة والتجارة: 588180",
    "Website: www.setatbyot.com\nEmail: info@setatbyot.com\nPhone: +962 7 8823 3400",
    "96265233400+\nAddress: مجمع السلام  الطابق الثالث ، شارع عارف العنبتاوي، الشميساني، عمّان، المملكة الأردنية الهاشمية."
  ],
  "en": [
    "SETAT BYOT LEGAL POLICIES AND TERMS",
    "Last Updated: 30 September 2026",
    "Operator Information",
    "The Setat Byot Platform is operated by:",
    "Registered Legal Name",
    "Setat Byot Establishment for Website Design and Data Updating",
    "Trading Name",
    "Setat Byot",
    "Government Tax Number",
    "9595473",
    "National Establishment Number",
    "101042113",
    "Ministry of Industry and Trade Registration Number",
    "588180",
    "Jurisdiction",
    "Hashemite Kingdom of Jordan",
    "Website",
    "www.setatbyot.com",
    "Email",
    "info@setatbyot.com",
    "Address",
    "Al Salam Complex, Aref Al-Anabtawi Street, Shmeisani, Amman, Jordan",
    "Telephone",
    "+962 6 523 3400 / +962 7 8823 3400",
    "The operator is referred to in these Policies as \"Setat Byot\", the \"Platform\", or \"we\".",
    "PART I – TERMS AND CONDITIONS OF USE",
    "1. Scope of the Service",
    "Setat Byot is an electronic platform and virtual marketplace connecting customers with a range of sellers and service providers, including home and production kitchens, catering service providers, artisans, home-based businesses, virtual bazaars, and other stores and products approved on the Platform.",
    "Depending on availability, the Platform’s services may include displaying products and services, receiving and managing orders, facilitating electronic payments, scheduling certain orders, providing or coordinating delivery services, order tracking, ratings, and support services.",
    "Unless clearly stated otherwise, the seller or service provider identified on the store page is the direct supplier of the product or service, while Setat Byot operates as an electronic platform that facilitates the completion of the transaction.",
    "Nothing in these Policies shall be interpreted as exempting Setat Byot or the seller from any obligation or liability that may not be excluded under Jordanian law.",
    "2. Acceptance of Terms",
    "By using the website or application, creating an account, placing an order, or registering as a seller, the user acknowledges that they have reviewed and understood these Policies and agree to comply with them.",
    "If the user does not agree to these Policies, they must not use services that require acceptance of them.",
    "3. Legal Capacity",
    "The user must have the legal capacity to enter into the relevant transaction.",
    "Use of the Platform by minors or persons who do not have full legal capacity must take place under the supervision and approval of a parent, guardian, or legal representative where required by law.",
    "4. User Accounts",
    "The user must provide accurate and up-to-date information, maintain the confidentiality of login credentials, and not allow unauthorised third parties to use the account.",
    "The Platform may take protective measures, including additional verification or temporary account suspension, where there is reasonable suspicion of fraud, unlawful use, or a security breach.",
    "The user must notify Setat Byot if they suspect that their account has been used without authorisation.",
    "5. Role of Setat Byot and the Seller",
    "Setat Byot seeks to work with sellers and service providers that meet its approved registration requirements.",
    "Each seller remains responsible for the products they prepare, manufacture, or display, including their condition, safety, description, quality, conformity with the order, and compliance with the licences and approvals required by the nature of their activity.",
    "Setat Byot may request documents or licences from a seller, or re-verify them, and may suspend or revoke approval of any seller or product where there are serious indications of a violation of law, safety requirements, or Platform policies.",
    "Approval of a seller does not constitute a permanent guarantee by Setat Byot that the seller will remain compliant at all times, and does not relieve Setat Byot of obligations imposed directly on it by law.",
    "6. Obligations of Kitchens and Food Sellers",
    "Each kitchen or food seller must obtain the valid licences and approvals required by the competent authorities to carry out its activity.",
    "Food may not be displayed or sold through the Platform by a home kitchen that does not meet the applicable licensing requirements in the Hashemite Kingdom of Jordan.",
    "Food sellers must comply with food safety, hygiene, storage, preparation, packaging, transportation, and appropriate temperature requirements according to the nature of the product.",
    "They must also provide an accurate description of the product and its main ingredients and reasonably disclose substances that may cause allergies where relevant.",
    "7. Food Allergies",
    "Food may contain ingredients or traces of ingredients that may cause allergic reactions, and more than one type of food may be prepared using shared facilities or equipment.",
    "A customer with a severe allergy or medically required dietary restrictions should verify the product details and inform the seller or customer service before completing the order where necessary.",
    "This section does not exempt any party from legal liability for providing false or misleading information or for supplying an unsafe product.",
    "8. Handicrafts and Non-Food Products",
    "The seller must ensure that the goods and handicrafts offered are safe, lawful, and consistent with the published description, images, and specifications.",
    "The sale of counterfeit, stolen, legally prohibited, or intellectual-property-infringing goods, or products whose circulation presents an undisclosed risk to the consumer, is prohibited.",
    "9. Information and Images",
    "The seller is responsible for the accuracy of the information they provide about their products, including images, prices, sizes, weights, ingredients, specifications, and preparation times.",
    "Some handmade or home-produced products may have minor and non-material differences from the images due to their handmade nature, provided that the difference is not material and does not make the product inconsistent with what was ordered.",
    "10. Orders",
    "Before an order is confirmed, the available information concerning the products, price, delivery fees, and any other applicable charges is displayed.",
    "Submission of an order does not constitute final acceptance until it is approved in accordance with the Platform’s process.",
    "An order may be rejected or cancelled in circumstances including product unavailability, inability of the seller to fulfil the order, an obvious pricing error, inability to complete payment, inability to deliver, reasonable suspicion of fraud, or circumstances beyond control.",
    "If an amount has been charged for an order that is cancelled for reasons not attributable to the customer, the amount due for refund will be processed in accordance with the Refund Policy.",
    "11. Prices",
    "Prices of products and services are displayed on the Platform before the order is confirmed.",
    "The final amount may include product prices, delivery fees, applicable taxes or charges, and any other amounts payable by the customer, provided that they are displayed before the purchase is confirmed.",
    "The final price displayed on the order confirmation page is the approved transaction price unless there is an obvious technical or pricing error such that the price cannot reasonably be considered correct.",
    "If an obvious error is discovered before fulfilment, the customer will be informed and given the options available under applicable law, including cancellation and refund of any amount already charged where appropriate.",
    "12. Offers and Vouchers",
    "Setat Byot or sellers may offer discounts, vouchers, or promotional offers subject to the published terms of each offer.",
    "Vouchers may not be exchanged for cash unless the offer or applicable law provides otherwise.",
    "Fraudulent or repeated use in violation of the offer conditions may be cancelled.",
    "PART II – ELECTRONIC PAYMENT POLICY",
    "13. Payment Methods",
    "Payment methods available on the Platform may include Visa and Mastercard cards, cash on delivery, and any additional payment methods adopted by Setat Byot.",
    "The payment methods actually available to the customer are displayed at checkout.",
    "14. Payment Gateway",
    "Card payments are processed by an authorised electronic payment service provider and may be processed through Middle East Payment Services – MEPS and/or another authorised payment provider contracted by Setat Byot.",
    "The customer may be redirected to a secure payment page operated by the payment provider to enter and verify card information.",
    "15. Card Information",
    "When payment is processed through the service provider’s secure payment page, Setat Byot does not store the complete card number or CVV/CVC on its servers.",
    "If the customer chooses the save-card feature, the payment provider may use a token or secure payment reference to enable future transactions without Setat Byot storing the complete card number.",
    "Setat Byot does not store the CVV/CVC for future payment transactions.",
    "16. Security Verification",
    "Payment transactions may require additional verification by the issuing bank, payment network, or payment gateway provider.",
    "The payment provider or bank may decline the transaction in accordance with its rules and security systems.",
    "17. Failed Payments",
    "If the financial transaction is not authorised, the order may not be created or confirmed.",
    "A temporary hold may appear on the amount at the bank even though the transaction was unsuccessful. In such cases, the time required to release the amount depends on the bank or payment provider.",
    "18. Duplicate Charges",
    "If the customer believes that the same transaction has been charged more than once, they should contact Setat Byot and provide the order number and any available transaction reference.",
    "Setat Byot will review its records and coordinate with the payment provider, and where a duplicate amount is confirmed, the necessary steps will be taken to refund it.",
    "19. Currency",
    "The customer is charged the amount and currency shown on the checkout page.",
    "Where the price is displayed in Jordanian Dinars, the transaction will be processed for the displayed amount in Jordanian Dinars unless different information is clearly shown before payment.",
    "The issuing bank may impose currency conversion fees or other banking charges where the card or account is held in a different currency. Such charges are not collected by Setat Byot.",
    "20. Fraud",
    "A transaction may be suspended, rejected, or cancelled where there are reasonable security indicators of unauthorised use or fraud, provided that this is done in a manner that does not conflict with consumer rights or applicable law.",
    "PART III – CANCELLATION, REFUND AND RETURN POLICY",
    "21. Standard Food Orders",
    "The customer may request cancellation before the seller accepts the order or before preparation begins, depending on the order status and Platform system.",
    "Once food preparation has begun, cancellation solely because the customer has changed their mind may not necessarily be available, due to the nature of fresh and made-to-order food.",
    "This does not affect the customer’s right to file a complaint or request compensation or a refund where there is a defect, non-conformity, or another issue recognised by law.",
    "22. Scheduled and Catering Orders",
    "Catering and event orders may require advance time reservations, the purchase of materials, allocation of labour, or special preparation.",
    "Special cancellation conditions may apply to such orders, provided that they are clearly displayed to the customer before the order is confirmed where a fee or specific cancellation deadline applies.",
    "If no special cancellation conditions were displayed when the booking was made, cancellation will be assessed according to the stage of order fulfilment and the reasonable, actual, non-recoverable costs directly incurred for the order, to the extent permitted by law.",
    "Undisclosed estimated or arbitrary lump-sum deductions will not be applied without a reasonable basis.",
    "23. Custom-Made Products",
    "For crafts or products manufactured or customised according to the customer’s specifications, cancellation due to a change of mind may not be possible once manufacturing or customisation has begun.",
    "This does not apply where the product is defective, does not conform to the agreed specifications, or is materially different from what was ordered.",
    "24. Cases Requiring Review and Refund",
    "The customer may request a review of the order in cases of non-delivery, cancellation after payment, delivery of the wrong product, a material shortage, damage or defect, an unsafe product, a material difference from the description, a duplicate charge, or any other case in which the law grants the customer a right.",
    "Reasonable photographs, details, or information may be requested to verify the case, provided that such procedures are not used arbitrarily to obstruct the customer’s legal rights.",
    "25. Refund Method",
    "Any amount due will normally be refunded to the original payment method where possible.",
    "In some cases permitted by law and accepted by the customer, in-app credit or another alternative form of compensation may be provided.",
    "A monetary refund that is legally due will not be replaced with in-app credit without the customer’s consent where the customer has a legal right to receive the amount through the original payment method.",
    "26. Refund Processing Time",
    "Setat Byot will initiate the refund process after approval without undue delay.",
    "The bank, payment provider, or card network may then require additional time for the amount to appear in the customer’s account, and this period is not fully under Setat Byot’s control.",
    "27. Non-Food Products",
    "If a non-food product is damaged, defective, materially different from its description, or a different product was sent instead, it will be handled in accordance with the consumer rights provided by law and the published policy.",
    "A non-defective product that conforms to the order is not returnable solely because of a change of mind unless the seller or Setat Byot has announced a voluntary return policy allowing this, or the law grants such a right.",
    "PART IV – DELIVERY POLICY",
    "28. Delivery Address",
    "The customer is responsible for entering an accurate address and contact information that enable delivery to be completed.",
    "Geographic location may be used to identify the address, calculate distance and delivery fees, and direct the driver.",
    "29. Delivery Times",
    "Any preparation or delivery time displayed on the Platform is an estimate unless expressly stated to be a binding time commitment.",
    "The duration may be affected by traffic, weather, order volume, seller delays, or unexpected circumstances.",
    "30. Tracking",
    "The customer may be able to track the order status and the driver’s location while the delivery is being carried out.",
    "The driver’s location is used for this purpose while the driver is Online or while carrying out an order, in accordance with system settings and the Privacy Policy.",
    "31. Unable to Reach the Customer",
    "If the driver arrives at the location and the customer cannot be contacted after reasonable attempts, appropriate action may be taken according to the nature of the product.",
    "It may not be safe to redeliver certain perishable food products after a prolonged period.",
    "This does not remove any customer right where delivery failure resulted from an error by the seller, driver, or Platform.",
    "32. Order Damaged During Delivery",
    "If an order is materially damaged during delivery, the customer should contact customer service as soon as reasonably possible. The matter will be investigated and an appropriate action taken, including replacement or refund where due.",
    "PART V – PRIVACY AND PERSONAL DATA PROTECTION POLICY",
    "33. Data Controller",
    "The Setat Byot Platform is operated by Setat Byot Establishment for Website Design and Data Updating.",
    "Personal data is processed in accordance with Jordanian Personal Data Protection Law and the applicable legislation, regulations, and instructions.",
    "34. Data We May Collect from Customers",
    "Depending on how the service is used, data may include name, telephone number, email address, delivery address, coordinates or location, account information, protected passwords, previous orders, favourite products, ratings, complaints and communications, device information, usage logs, IP address, technical and security information, and limited financial transaction information.",
    "35. Seller Data",
    "Seller data may include the name of the individual or establishment, identification or verification documents, contact information, business address and location, licences and permits, store and product information, photographs, financial account or settlement details, order and sales history, commissions, and amounts withdrawn.",
    "36. Driver Data",
    "Driver data may include name, contact information, identification, driving licence, vehicle information and documents, the driver’s location while working, delivery history, earnings, and ratings.",
    "37. Payment Information",
    "When a secure payment page operated by the payment provider is used, Setat Byot does not store the complete card number or CVV/CVC.",
    "The Platform may receive a transaction reference number, payment status, card type, masked card information, or a secure token depending on the method of integration with the payment provider.",
    "38. Purposes of Data Processing",
    "Data may be processed to create and manage accounts, provide the service, fulfil orders, calculate delivery, process payments, connect the customer with the seller and driver, manage orders and refunds, provide technical support and customer service, detect and prevent fraud, protect the Platform, comply with law, manage accounts and amounts due, improve the service, and send marketing communications where an appropriate legal basis and the required consents are available.",
    "39. Geographic Location",
    "The customer application may use location information to display nearby sellers, determine the delivery address, calculate fees, and track the order.",
    "The driver application may use location, including background location while the driver is Online where necessary, to display nearby orders, manage deliveries, and enable the customer to track their order.",
    "Collection of the driver’s location for delivery purposes should not continue after the driver switches to Offline status, except where legally or technically necessary to complete a process that has already begun.",
    "40. Data Sharing",
    "Necessary data may be shared with the seller to fulfil the order, the driver to complete delivery, the payment provider to process the transaction, providers of hosting, technology, maps, messaging, notifications, analytics, and security services where such services are used, professional advisers, and official authorities where required or permitted by law.",
    "Disclosure will be limited, as far as reasonably possible, to the data necessary for the relevant purpose.",
    "Setat Byot does not sell customers’ personal data to advertisers.",
    "41. Customer Data Visible to the Seller or Driver",
    "The seller and driver receive only the information necessary to fulfil the order according to their respective roles.",
    "The seller or driver may not use customer data for personal purposes or independent marketing purposes, or retain it outside approved systems in an unlawful manner.",
    "42. Consent and Lawful Basis",
    "Consent will be obtained where the law requires prior consent, and any other lawful basis permitted by law may be relied upon where applicable.",
    "Information concerning the purpose of collecting the data, its scope, and the parties that may receive it will be provided in accordance with applicable legal requirements.",
    "43. Rights of the Data Subject",
    "Subject to applicable law and procedures, the data subject has rights that may include knowing what data is being processed, accessing and obtaining it, correcting and updating it, withdrawing consent where processing is based on consent, restricting processing within a defined scope, requesting erasure or concealment where permitted by law, objecting to certain types of processing or profiling, transferring a copy of the data where the right applies, and being informed of incidents affecting the security and integrity of their data in accordance with law.",
    "Requests may be sent to:",
    "info@setatbyot.com",
    "Appropriate information may be requested to verify the identity of the person submitting the request.",
    "44. Marketing",
    "Offers and marketing notifications may be sent where permitted by law.",
    "The user may opt out of non-essential marketing communications using the method available in the application or message.",
    "Opting out of marketing does not affect necessary communications relating to orders, payments, the account, or security.",
    "45. Cookies and Similar Technologies",
    "The website may use cookies or similar technologies to operate the service, remember user preferences, protect the account, measure performance, and improve the user experience.",
    "Where the law requires consent for certain types of such technologies, the appropriate consent will be requested.",
    "46. Retention Period",
    "Setat Byot does not retain data indefinitely without a reason.",
    "Data is retained for the period necessary to fulfil orders, manage accounts, settle payments, resolve disputes, and satisfy tax, accounting, regulatory, and security obligations. Thereafter, it is deleted or anonymised when retention is no longer necessary, unless another legal obligation requires continued retention.",
    "47. Transfer of Data Outside Jordan",
    "Some technical services may host or process data in other countries.",
    "In such cases, transfers will be handled in accordance with the requirements of Jordanian Personal Data Protection Law and any applicable regulations or instructions concerning data transfers and the required level of protection.",
    "48. Information Security",
    "Setat Byot uses reasonable technical and organisational measures appropriate to the nature of the data and the risks associated with its processing.",
    "No electronic system can be guaranteed to be 100% secure; however, the Platform works to reduce the risks of unauthorised access, use, or disclosure.",
    "Any security incident involving personal data will be handled in accordance with applicable legal procedures and requirements.",
    "49. Children",
    "The Platform is not intended to independently collect children’s data without an appropriate legal basis.",
    "Where consent from a parent, guardian, or legal representative is required to process a minor’s data, it must be obtained in accordance with law.",
    "50. Data Protection Officer",
    "The Establishment will appoint and accredit a personal data protection officer where any of the cases requiring such appointment under applicable law apply.",
    "Once an official officer is appointed, their contact information or a dedicated channel for personal data protection requests may be published.",
    "PART VI – SELLER POLICY AND TERMS",
    "51. Seller Registration",
    "An applicant must provide Setat Byot with accurate and complete information and the documents required to verify their identity and activity.",
    "Submitting an application does not automatically constitute approval to open a store.",
    "52. Licences",
    "The seller is responsible for obtaining and renewing all licences and approvals required for their activity.",
    "Continued validity of such documents is a condition for continuing to offer products where the nature of the activity requires them.",
    "53. Home Kitchens",
    "A home food seller may not use the Platform to sell food products if they are not legally authorised to carry out the activity or do not hold the required licences and approvals.",
    "Setat Byot may immediately suspend a store where a licence expires, inaccurate information is discovered, notice is received from an official authority, or a serious risk to public health arises.",
    "54. Pricing and Inventory",
    "The seller is responsible for accurately updating prices, inventory, working hours, and preparation times.",
    "The price may not be increased after the customer’s order has been accepted except with the customer’s express consent where permitted by law.",
    "55. Acceptance of Orders",
    "The seller must accept or reject an order within a reasonable time and work to prepare an accepted order according to the agreed details.",
    "Repeated acceptance and subsequent cancellation of orders without a legitimate reason may result in action being taken on the account.",
    "56. Commission and Amounts Due",
    "Setat Byot’s commission and any service-related fees are determined in accordance with the seller agreement or the information displayed in the seller dashboard.",
    "The seller must review commission, amounts due, and settlement details before using the commercial service.",
    "This Policy does not, by itself, replace any separate commercial agreement specifying percentages, transfer dates, and settlement arrangements.",
    "57. Taxes",
    "Each party is responsible for the tax obligations imposed on it by law.",
    "The seller must provide any information, invoices, or documents required by law according to the nature of the seller’s activity.",
    "58. Cancellations and Refunds Caused by Seller Error",
    "If a refund is issued to a customer due to a missing, incorrect, defective, or unsafe product, or because the seller failed to fulfil the order, the amount or the portion attributable to the error may be charged to the seller’s account in accordance with the seller agreement and applicable law after reasonable verification of the circumstances.",
    "59. Complaints and Investigation",
    "The seller must cooperate with investigations concerning customer complaints and provide the necessary information within a reasonable period.",
    "Setat Byot may refund the customer or take temporary action where there is a health or fraud risk or where the facts are clear, while taking into account the rights of all parties.",
    "60. Seller Content",
    "The seller grants Setat Byot a non-exclusive licence to use the images, names, logos, and descriptions they provide to the extent necessary to display and promote the seller’s store and products and operate Platform services.",
    "The seller confirms that they have the right to use the content they upload.",
    "61. Prohibited Practices",
    "The seller is prohibited from providing misleading information, manipulating ratings, selling unlawful products, using customer information outside the scope of fulfilling the order, attempting to defraud the payment or commission system, or publishing content that infringes the rights of others.",
    "62. Store Suspension",
    "A store may be suspended, restricted, or closed in cases of material violation, health risks, fraud, expiry of required licences, repeated substantiated complaints, or violation of law or Platform terms.",
    "Where the nature of the violation permits, the seller may be informed of the reason for the action and given an opportunity to provide an explanation or remedy the violation.",
    "PART VII – RATINGS AND CONTENT",
    "63. Customer Ratings",
    "The customer may rate their experience after completing an order.",
    "The rating must be based on a genuine experience and must not contain threats, abuse, discrimination, unlawful defamation, another person’s personal information, or content that violates the law.",
    "Non-compliant content may be removed, but legitimate criticism will not be removed merely because it is negative.",
    "PART VIII – LIABILITY",
    "64. Seller Liability",
    "The seller is responsible for the safety, quality, and conformity of the products they manufacture, prepare, or sell, for the accuracy of the related information, and for ensuring that their activity complies with the relevant legal requirements.",
    "65. Setat Byot Liability",
    "Setat Byot remains responsible for its obligations as the operator of the Platform in relation to services it provides directly, including obligations imposed by law regarding information, privacy, complaint handling, payments, and technical services.",
    "Setat Byot is not responsible for a loss caused exclusively by inaccurate information provided by the user or an event reasonably outside the Platform’s control.",
    "No limitation of liability shall be interpreted as excluding liability that may not lawfully be excluded.",
    "66. Circumstances Beyond Control",
    "Services may be affected by circumstances reasonably beyond control, such as severe weather, road closures, disasters, telecommunications or payment-system outages, official decisions, or force majeure events.",
    "Setat Byot will work to reduce the impact of such circumstances and handle affected orders in a reasonable manner.",
    "PART IX – INTELLECTUAL PROPERTY",
    "67. Setat Byot Rights",
    "Rights in the Setat Byot name, Platform designs, software, and content owned by the Establishment belong to their lawful owners.",
    "The Platform may not be copied or commercially exploited without consent or a lawful right.",
    "68. Seller Rights",
    "The seller retains their rights in photographs, trademarks, and content owned by them, subject to the limited licence granted to the Platform for the operation, display, and marketing of the seller’s store.",
    "PART X – ACCOUNT SUSPENSION AND TERMINATION",
    "69. User Account Closure",
    "A user may request closure of their account, subject to retention of data that must be retained by law or that is necessary to settle outstanding transactions or disputes.",
    "70. Account Suspension",
    "An account may be suspended where there is a serious violation or security or fraud risk, and the action should be proportionate to the nature of the violation as far as reasonably possible.",
    "PART XI – COMPLAINTS AND DISPUTE RESOLUTION",
    "71. Complaints",
    "Customers and sellers are encouraged to contact Setat Byot first regarding any complaint relating to an order, payment, refund, or account.",
    "Email: info@setatbyot.com",
    "Telephone: +962 7 8823 3400",
    "Setat Byot will review the complaint and the available information and seek to reach an appropriate resolution.",
    "These procedures do not prevent any person from exercising the right to file a complaint with the competent governmental or regulatory authorities or to resort to the courts.",
    "72. Governing Law",
    "These Policies are governed by the laws of the Hashemite Kingdom of Jordan.",
    "Any dispute shall be subject to the competent Jordanian authorities and courts in accordance with applicable jurisdiction rules, while preserving consumer rights, data-subject rights, and any other mandatory rights granted by law.",
    "PART XII – AMENDMENTS TO THESE POLICIES",
    "73. Updates",
    "These Policies may be updated when the service or legal or operational requirements change.",
    "The updated version will be published together with the date of the latest update.",
    "Where a material amendment requires renewed consent or special notice under applicable law, Setat Byot will take the necessary steps.",
    "PART XIII – LANGUAGE",
    "74. Arabic and English",
    "These Policies are available in Arabic and English, and both versions are intended to express the same terms.",
    "In the event of an unintended difference in meaning or interpretation, the Arabic version shall be the reference for dealings within the Hashemite Kingdom of Jordan to the extent permitted by law.",
    "CONTACT US",
    "Setat Byot Establishment for Website Design and Data Updating",
    "Trading as Setat Byot",
    "Government Tax Number: 9595473",
    "National Establishment Number: 101042113",
    "Ministry of Industry and Trade Registration Number: 588180",
    "Website: www.setatbyot.com",
    "Email: info@setatbyot.com",
    "Phone: +962 7 8823 3400",
    "Phone: +962 6 523 3400",
    "Address: Al Salam Complex, 3rd Floor, Aref Al-Anabtawi Street, Shmeisani, Amman, Hashemite Kingdom of Jordan."
  ]
};

type LegalPoliciesProps = { onClose: () => void };

export default function LegalPolicies({ onClose }: LegalPoliciesProps) {
  const { language, toggleLanguage, t } = useLanguage();
  const isArabic = language === 'ar';
  const paragraphs = POLICY_PARAGRAPHS[language];
  const [title, ...body] = paragraphs;
  const bodyFont = isArabic ? 'var(--font-arabic)' : 'var(--font-sans)';
  const headingFont = isArabic ? 'var(--font-arabic)' : 'var(--font-serif)';
  const controlStyle = {
    border: '1px solid var(--accent-border)',
    borderRadius: '999px',
    padding: '8px 14px',
    color: 'var(--accent)',
    background: 'transparent',
    fontFamily: bodyFont,
    fontSize: '0.85rem',
    cursor: 'pointer',
  } as const;
  const isPartHeading = (text: string) => /^(PART\s+[IVXLCDM]+|الجزء\s)/i.test(text);
  const isSectionHeading = (text: string) => /^\d{1,2}\.\s/.test(text);
  const isSubheading = (text: string) => /^(Operator Information|بيانات الجهة المشغلة|CONTACT US|التواصل معنا)$/i.test(text);
  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={isArabic ? 'السياسات والشروط القانونية' : 'Legal Policies and Terms'}
      dir={isArabic ? 'rtl' : 'ltr'}
      lang={language}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 3000,
        overflowY: 'auto',
        backgroundColor: 'var(--background)',
        color: 'var(--foreground)',
      }}
    >
      <header style={{ position: 'sticky', top: 0, zIndex: 1, borderBottom: '1px solid var(--border)', backgroundColor: 'var(--background)' }}>
        <div style={{ maxWidth: '960px', margin: '0 auto', padding: '14px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' }}>
          <span style={{ fontFamily: bodyFont, fontWeight: 600, fontSize: '0.92rem' }}>
            {isArabic ? 'السياسات والشروط القانونية' : 'Legal Policies & Terms'}
          </span>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <button type="button" onClick={toggleLanguage} style={controlStyle}>
              {t('nav.switchLang')}
            </button>
            <button type="button" onClick={onClose} aria-label={isArabic ? 'إغلاق السياسات' : 'Close policies'} style={{ ...controlStyle, width: '40px', height: '40px', padding: 0, fontSize: '1.4rem', lineHeight: 1 }}>
              ×
            </button>
          </div>
        </div>
      </header>
      <main style={{ maxWidth: '900px', margin: '0 auto', padding: '34px 24px 80px', fontFamily: bodyFont, lineHeight: isArabic ? 2 : 1.8 }}>
        <h1 style={{ fontFamily: headingFont, fontSize: 'clamp(1.8rem, 4vw, 2.7rem)', lineHeight: 1.25, color: 'var(--foreground)', margin: '0 0 12px' }}>
          {title}
        </h1>
        {body.map((paragraph, index) => {
          if (isPartHeading(paragraph) || isSubheading(paragraph)) {
            return <h2 key={index} style={{ fontFamily: headingFont, fontSize: '1.35rem', lineHeight: 1.5, color: 'var(--accent)', margin: '34px 0 14px' }}>{paragraph}</h2>;
          }
          if (isSectionHeading(paragraph)) {
            return <h3 key={index} style={{ fontFamily: bodyFont, fontSize: '1.05rem', lineHeight: 1.6, color: 'var(--foreground)', margin: '24px 0 8px', fontWeight: 700 }}>{paragraph}</h3>;
          }
          if (/^(Last Updated:|آخر تحديث:)/.test(paragraph)) {
            return <p key={index} style={{ color: 'var(--muted-foreground)', fontSize: '0.9rem', margin: '0 0 24px' }}>{paragraph}</p>;
          }
          return <p key={index} style={{ whiteSpace: 'pre-wrap', margin: '0 0 14px', color: 'var(--muted-foreground)' }}>{paragraph}</p>;
        })}
      </main>
    </div>
  );
}
